In [2]:
import pathlib as Path
import numpy as np
import pandas as pd

## Create dataframe from embeddings

In [23]:
#-----Frequency Embeddings dataframe creation-----
def create_embeddings_dataframe(root_path):
    emb_root = Path.Path(root_path)
    emb_files = emb_root.rglob("embeddings_samples.npz")
    
    all_data = []
    
    for emb_file in emb_files:
        emb = np.load(emb_file)
        X = emb['X']
        y = emb['y']
        subjects = emb['subs']
        
        for i in range(X.shape[0]):
            data_point = {
                'embedding': X[i],
                'label': y[i],
                'subject': subjects[i],
                'file_path': str(emb_file)
            }
            all_data.append(data_point)
    
    df = pd.DataFrame(all_data)
    return df

In [24]:
def df_cleaning(df, emb_size=384):
        # --- Expand embedding column into 381 separate columns ---
    embedding_df = pd.DataFrame(df["embedding"].tolist(),
                                columns=[f"emb_{i}" for i in range(emb_size)])

    # --- Concatenate back to the original DataFrame (optional) ---
    df_expanded = pd.concat([df.drop(columns=["embedding"]), embedding_df], axis=1)
    return df_expanded

In [25]:
#-----Frequency Embeddings dataframe creation-----
freq_emb= create_embeddings_dataframe("C://dev//dolphin_initial_testing//DOLPHIN//out_prelbd_task_wise//frequency_emb_stored//")
#-----Temporal Embeddings dataframe creation-----
temp_emb= create_embeddings_dataframe("C://dev//dolphin_initial_testing//DOLPHIN//out_prelbd_task_wise//temporal_emb_stored//")
#-----Combined Embeddings dataframe creation-----
emb= create_embeddings_dataframe("C://dev//dolphin_initial_testing//DOLPHIN//out_prelbd_task_wise//emb_stored//")

freq_emb_df= df_cleaning(freq_emb, emb_size=384)
temp_emb_df= df_cleaning(temp_emb, emb_size=384)
emb_df= df_cleaning(emb, emb_size=768)

In [34]:
freq_emb_df.sample(5)

,label,subject,file_path,emb_0,emb_1,emb_2,emb_3,emb_4,emb_5,emb_6,...,emb_374,emb_375,emb_376,emb_377,emb_378,emb_379,emb_380,emb_381,emb_382,emb_383
271,1,pre-LBD-79#1,C:\dev\dolphin_initial_testing\DOLPHIN\out_pre...,0.029030,-0.036020,0.014511,-0.046278,0.024597,-0.029768,0.052036,...,0.020099,0.130927,-0.035791,0.021649,-0.003429,0.110006,0.005901,0.028940,0.027033,0.049797
1831,1,pre-LBD-33#1,C:\dev\dolphin_initial_testing\DOLPHIN\out_pre...,-0.015723,-0.009043,-0.042634,0.038719,-0.020010,0.023625,0.045671,...,0.018789,-0.052624,-0.060718,0.011255,0.051979,0.107696,-0.020102,0.036647,-0.046535,0.053375
1716,1,pre-LBD-60#1,C:\dev\dolphin_initial_testing\DOLPHIN\out_pre...,0.043170,0.030425,0.030970,-0.070260,0.000704,-0.075280,0.026119,...,-0.015373,0.037654,0.063299,-0.049393,-0.066511,-0.011848,-0.126985,-0.003583,-0.016407,-0.121498
1527,1,pre-LBD-20#1,C:\dev\dolphin_initial_testing\DOLPHIN\out_pre...,-0.055669,-0.007522,-0.064244,0.080196,-0.016317,-0.035736,0.074589,...,0.079729,-0.013251,0.047741,-0.071851,-0.005657,0.051364,-0.016885,-0.062887,-0.013071,-0.010138
1788,0,HC-9#1,C:\dev\dolphin_initial_testing\DOLPHIN\out_pre...,-0.022750,-0.013895,-0.049083,0.038597,-0.020563,0.029038,0.045185,...,0.023945,-0.056518,-0.061066,0.013066,0.048103,0.122344,-0.026337,0.040859,-0.053087,0.057095

In [35]:
temp_emb_df.sample(5)

,label,subject,file_path,emb_0,emb_1,emb_2,emb_3,emb_4,emb_5,emb_6,...,emb_374,emb_375,emb_376,emb_377,emb_378,emb_379,emb_380,emb_381,emb_382,emb_383
300,0,HC-15#1,C:\dev\dolphin_initial_testing\DOLPHIN\out_pre...,0.028693,0.025202,-0.086923,-0.021497,0.030245,-0.012504,0.020676,...,0.143298,0.035069,-0.037009,0.090912,0.077990,-0.111565,-0.079321,0.026469,0.006764,0.036067
839,1,pre-LBD-64#1,C:\dev\dolphin_initial_testing\DOLPHIN\out_pre...,-0.029253,-0.022407,0.000335,0.082588,0.024136,-0.026781,-0.036897,...,-0.003187,0.005005,-0.074295,0.036953,-0.064724,-0.058763,0.044307,0.010134,0.065696,-0.043494
687,1,pre-LBD-54#1,C:\dev\dolphin_initial_testing\DOLPHIN\out_pre...,-0.007239,0.085514,0.036406,-0.092364,0.010524,-0.046187,-0.014637,...,-0.045078,0.004097,-0.015976,0.017227,-0.017004,0.048956,0.041767,-0.066096,-0.020192,-0.011305
320,0,HC-33#1,C:\dev\dolphin_initial_testing\DOLPHIN\out_pre...,0.029336,0.025375,-0.084674,-0.020165,0.029911,-0.013395,0.019406,...,0.144405,0.036456,-0.038051,0.092623,0.077913,-0.112993,-0.077762,0.024028,0.008534,0.035404
1439,1,pre-LBD-78#1,C:\dev\dolphin_initial_testing\DOLPHIN\out_pre...,-0.076946,0.034216,-0.034888,-0.018194,0.084529,0.031079,-0.004810,...,-0.046679,0.047226,-0.004347,0.081521,0.018846,0.035627,-0.006357,0.065003,0.021144,-0.018524

In [36]:
emb_df.sample(5)

,label,subject,file_path,emb_0,emb_1,emb_2,emb_3,emb_4,emb_5,emb_6,...,emb_758,emb_759,emb_760,emb_761,emb_762,emb_763,emb_764,emb_765,emb_766,emb_767
137,1,pre-LBD-90#1,C:\dev\dolphin_initial_testing\DOLPHIN\out_pre...,-0.008063,-0.086463,0.004239,-0.019041,-0.021192,0.045932,-0.060451,...,0.030729,-0.017207,-0.023212,0.013957,-0.006783,0.012540,-0.076508,0.006332,-0.023037,0.002888
1386,1,pre-LBD-26#1,C:\dev\dolphin_initial_testing\DOLPHIN\out_pre...,0.004375,0.033727,0.044324,-0.018112,-0.000496,-0.049241,0.025182,...,-0.001025,0.036461,0.026297,0.031151,0.018530,0.027967,-0.036846,-0.027342,0.005197,-0.053160
1888,1,pre-LBD-9#1,C:\dev\dolphin_initial_testing\DOLPHIN\out_pre...,0.010956,0.010304,-0.002053,-0.035403,-0.001959,0.025740,-0.053957,...,0.043063,0.026588,-0.007693,0.035790,0.034714,-0.019034,-0.022789,0.039877,0.018712,-0.014998
76,1,pre-LBD-32#1,C:\dev\dolphin_initial_testing\DOLPHIN\out_pre...,-0.007696,-0.084700,0.001654,-0.021324,-0.018293,0.047279,-0.069651,...,0.030935,-0.016558,-0.023132,0.013076,-0.009474,0.011282,-0.079419,0.001146,-0.014324,0.004606
650,1,pre-LBD-19#1,C:\dev\dolphin_initial_testing\DOLPHIN\out_pre...,-0.047123,0.027796,0.019533,-0.027939,0.001537,-0.063707,-0.035895,...,-0.022926,0.021705,0.034009,0.059643,-0.037481,0.015193,0.001100,0.075674,-0.045403,0.034297