In [2]:
import pathlib as Path
import numpy as np
import pandas as pd

## Create dataframe from embeddings

In [23]:
#-----Frequency Embeddings dataframe creation-----
def create_embeddings_dataframe(root_path):
    emb_root = Path.Path(root_path)
    emb_files = emb_root.rglob("embeddings_samples.npz")
    
    all_data = []
    
    for emb_file in emb_files:
        emb = np.load(emb_file)
        X = emb['X']
        y = emb['y']
        subjects = emb['subs']
        
        for i in range(X.shape[0]):
            data_point = {
                'embedding': X[i],
                'label': y[i],
                'subject': subjects[i],
                'file_path': str(emb_file)
            }
            all_data.append(data_point)
    
    df = pd.DataFrame(all_data)
    return df

In [42]:
def df_cleaning(df, emb_size=384):
        # --- Expand embedding column into 381 separate columns ---
    embedding_df = pd.DataFrame(df["embedding"].tolist(),
                                columns=[f"emb_{i}" for i in range(emb_size)])

    # --- Concatenate back to the original DataFrame (optional) ---
    df_expanded = pd.concat([df.drop(columns=["embedding"]), embedding_df], axis=1)
    return df_expanded

In [43]:
#-----Frequency Embeddings dataframe creation-----
freq_emb= create_embeddings_dataframe("C://dev//dolphin_initial_testing//DOLPHIN//out_prelbd_task_wise//frequency_emb_stored//")
#-----Temporal Embeddings dataframe creation-----
temp_emb= create_embeddings_dataframe("C://dev//dolphin_initial_testing//DOLPHIN//out_prelbd_task_wise//temporal_emb_stored//")
#-----Combined Embeddings dataframe creation-----
comb_emb= create_embeddings_dataframe("C://dev//dolphin_initial_testing//DOLPHIN//out_prelbd_task_wise//emb_stored//")

freq_emb_df= df_cleaning(freq_emb, emb_size=384)
temp_emb_df= df_cleaning(temp_emb, emb_size=384)
comb_emb_df= df_cleaning(comb_emb, emb_size=768)

In [46]:
freq_emb_df.sample(5)

,label,subject,file_path,emb_0,emb_1,emb_2,emb_3,emb_4,emb_5,emb_6,...,emb_374,emb_375,emb_376,emb_377,emb_378,emb_379,emb_380,emb_381,emb_382,emb_383
1261,1,pre-LBD-48#1,C:\dev\dolphin_initial_testing\DOLPHIN\out_pre...,-0.057220,-0.045030,-0.079478,-0.056853,-0.017878,-0.053643,0.034002,...,0.078174,0.070206,-0.055958,-0.043614,0.015236,0.033748,0.033059,-0.058145,-0.010648,0.023852
309,0,HC-23#1,C:\dev\dolphin_initial_testing\DOLPHIN\out_pre...,0.031417,-0.101307,0.046721,0.026445,-0.026174,0.121052,0.007979,...,0.047567,0.061747,0.067212,0.014017,0.030327,0.020516,-0.034606,0.072241,-0.002285,0.021234
1598,1,pre-LBD-89#1,C:\dev\dolphin_initial_testing\DOLPHIN\out_pre...,-0.056319,-0.006328,-0.063812,0.081784,-0.015128,-0.037805,0.072567,...,0.080671,-0.012862,0.046177,-0.073255,-0.009231,0.052581,-0.016649,-0.060984,-0.012464,-0.010481
950,1,pre-LBD-31#1,C:\dev\dolphin_initial_testing\DOLPHIN\out_pre...,-0.008864,-0.118023,-0.097423,0.007379,-0.033725,-0.040583,0.061643,...,0.023511,0.096039,0.023408,-0.030540,0.054625,0.029039,0.098773,-0.011357,0.021005,-0.046258
1820,1,pre-LBD-21#1,C:\dev\dolphin_initial_testing\DOLPHIN\out_pre...,-0.011896,-0.002613,-0.042516,0.039896,-0.020128,0.025562,0.047391,...,0.020053,-0.052420,-0.060157,0.014583,0.052681,0.100672,-0.018075,0.032760,-0.044750,0.051293

In [47]:
temp_emb_df.sample(5)

,label,subject,file_path,emb_0,emb_1,emb_2,emb_3,emb_4,emb_5,emb_6,...,emb_374,emb_375,emb_376,emb_377,emb_378,emb_379,emb_380,emb_381,emb_382,emb_383
1510,1,pre-LBD-113#1,C:\dev\dolphin_initial_testing\DOLPHIN\out_pre...,0.045023,0.027845,0.009193,0.082467,0.044448,-0.085570,0.020873,...,0.031141,0.032681,-0.064488,-0.036170,0.044042,0.099258,0.041540,-0.008353,-0.025521,-0.048977
1245,1,pre-LBD-32#1,C:\dev\dolphin_initial_testing\DOLPHIN\out_pre...,-0.016142,-0.005171,-0.003530,-0.015881,0.039155,0.033295,-0.024593,...,0.037208,0.034744,0.037302,-0.034430,0.012691,0.064173,0.020588,0.015866,0.028081,0.018506
1173,0,HC-13#1,C:\dev\dolphin_initial_testing\DOLPHIN\out_pre...,-0.012934,0.002142,-0.006851,-0.016728,0.030206,0.032310,-0.026470,...,0.041157,0.032667,0.043471,-0.036817,0.007385,0.063885,0.023800,0.013747,0.029160,0.021303
874,1,pre-LBD-99#1,C:\dev\dolphin_initial_testing\DOLPHIN\out_pre...,-0.032033,-0.022525,0.000123,0.086882,0.026234,-0.023139,-0.040024,...,0.000702,0.003611,-0.070436,0.034819,-0.062500,-0.056857,0.045833,0.010659,0.064207,-0.043515
655,1,pre-LBD-23#1,C:\dev\dolphin_initial_testing\DOLPHIN\out_pre...,-0.005479,0.090195,0.037274,-0.093366,0.013254,-0.047957,-0.015377,...,-0.044516,0.005128,-0.015878,0.014426,-0.020289,0.052245,0.046013,-0.063357,-0.019135,-0.016780

In [48]:
comb_emb_df.sample(5)

,label,subject,file_path,emb_0,emb_1,emb_2,emb_3,emb_4,emb_5,emb_6,...,emb_758,emb_759,emb_760,emb_761,emb_762,emb_763,emb_764,emb_765,emb_766,emb_767
101,1,pre-LBD-56#1,C:\dev\dolphin_initial_testing\DOLPHIN\out_pre...,-0.006220,-0.089246,0.005896,-0.023443,-0.017367,0.040997,-0.058958,...,0.028839,-0.015881,-0.023046,0.015676,-0.004685,0.012080,-0.074097,0.002498,-0.022346,0.002338
1002,1,pre-LBD-81#1,C:\dev\dolphin_initial_testing\DOLPHIN\out_pre...,0.057589,-0.000993,0.022673,-0.042429,0.004056,0.037034,-0.015798,...,0.016417,-0.092221,-0.013532,-0.033003,0.000654,0.033992,0.016463,-0.021810,-0.020118,0.012665
1550,1,pre-LBD-42#1,C:\dev\dolphin_initial_testing\DOLPHIN\out_pre...,0.003270,-0.048533,0.052353,0.018464,-0.086642,-0.025933,-0.013564,...,0.050600,-0.059640,0.008794,-0.024249,0.026868,0.021335,0.015163,0.008743,0.046388,0.011361
381,1,pre-LBD-42#1,C:\dev\dolphin_initial_testing\DOLPHIN\out_pre...,0.038141,-0.003109,0.004478,0.029802,0.044367,-0.022703,-0.063533,...,0.000501,-0.002479,-0.044631,0.060143,0.000394,-0.052529,-0.008801,-0.003698,0.003991,0.036822
936,1,pre-LBD-18#1,C:\dev\dolphin_initial_testing\DOLPHIN\out_pre...,0.056422,0.000550,0.020824,-0.041429,0.004896,0.034796,-0.016136,...,0.016203,-0.091815,-0.014255,-0.034148,0.001361,0.034776,0.016377,-0.020596,-0.020691,0.012280

In [49]:
def task_wise_df_creation(df, task_name):
    task_df = df[df['file_path'].str.contains(task_name)].reset_index(drop=True)
    return task_df

In [50]:
task_list = ['1_1', '3_1', '3_2', '3_3', '3_4', '3_5', '9_1', '10_1', '15_1', '16_1', '17_1', '18_1', '19_1']

task_freq_dfs = {task: task_wise_df_creation(freq_emb_df, task) for task in task_list}
task_temp_dfs = {task: task_wise_df_creation(freq_emb_df, task) for task in task_list}
task_comb_dfs = {task: task_wise_df_creation(freq_emb_df, task) for task in task_list}

In [57]:
task_freq_dfs.get("3_1").sample(15)

,label,subject,file_path,emb_0,emb_1,emb_2,emb_3,emb_4,emb_5,emb_6,...,emb_374,emb_375,emb_376,emb_377,emb_378,emb_379,emb_380,emb_381,emb_382,emb_383
107,1,pre-LBD-61#1,C:\dev\dolphin_initial_testing\DOLPHIN\out_pre...,0.031036,0.082003,-0.017964,0.008294,-0.115811,-0.025145,-0.033388,...,0.037425,-0.039711,0.021668,-0.004804,-0.050383,0.033685,-0.065739,-0.011091,0.003354,-0.059080
9,0,HC-18#1,C:\dev\dolphin_initial_testing\DOLPHIN\out_pre...,0.021628,0.082798,-0.010443,0.010831,-0.115125,-0.028201,-0.036203,...,0.035444,-0.036047,0.022388,-0.003138,-0.047997,0.039544,-0.064802,-0.017963,0.001914,-0.058502
126,1,pre-LBD-80#1,C:\dev\dolphin_initial_testing\DOLPHIN\out_pre...,0.021155,0.080457,-0.013246,0.008868,-0.109775,-0.028651,-0.033410,...,0.034169,-0.028815,0.020389,0.001274,-0.049289,0.037772,-0.063961,-0.016367,-0.003361,-0.063248
95,1,pre-LBD-50#1,C:\dev\dolphin_initial_testing\DOLPHIN\out_pre...,0.021334,0.081776,-0.009290,0.007749,-0.114249,-0.030727,-0.032800,...,0.033560,-0.033826,0.021484,-0.004053,-0.051208,0.039891,-0.062264,-0.019132,-0.001546,-0.060453
21,0,HC-29#1,C:\dev\dolphin_initial_testing\DOLPHIN\out_pre...,0.016058,0.082294,-0.007299,0.012288,-0.117392,-0.031998,-0.035507,...,0.032507,-0.033877,0.022312,-0.003566,-0.047770,0.041086,-0.062655,-0.016523,-0.002900,-0.055798
44,1,pre-LBD-110#1,C:\dev\dolphin_initial_testing\DOLPHIN\out_pre...,0.019486,0.081165,-0.007947,0.009855,-0.112831,-0.031096,-0.033666,...,0.035257,-0.031539,0.022073,-0.002924,-0.050904,0.041601,-0.062378,-0.020166,-0.000210,-0.059437
57,1,pre-LBD-14#1,C:\dev\dolphin_initial_testing\DOLPHIN\out_pre...,0.015944,0.080661,-0.006830,0.010052,-0.115370,-0.033410,-0.033333,...,0.029632,-0.032336,0.021827,-0.003415,-0.049775,0.042920,-0.060795,-0.020692,-0.004642,-0.056170
7,0,HC-16#1,C:\dev\dolphin_initial_testing\DOLPHIN\out_pre...,0.018267,0.081425,-0.006669,0.011286,-0.116775,-0.033066,-0.033758,...,0.032615,-0.033264,0.022481,-0.005002,-0.050897,0.042882,-0.060828,-0.020436,-0.001590,-0.055785
27,0,HC-34#1,C:\dev\dolphin_initial_testing\DOLPHIN\out_pre...,0.021228,0.081235,-0.010565,0.006577,-0.114682,-0.028940,-0.032006,...,0.034517,-0.034152,0.021148,-0.002226,-0.050340,0.038306,-0.063057,-0.016370,-0.001951,-0.060489
38,1,pre-LBD-103#1,C:\dev\dolphin_initial_testing\DOLPHIN\out_pre...,0.020236,0.081759,-0.008424,0.009276,-0.115209,-0.030145,-0.032695,...,0.032214,-0.032790,0.021979,-0.002656,-0.051434,0.039761,-0.061657,-0.019571,-0.002411,-0.058873
46,1,pre-LBD-112#1,C:\dev\dolphin_initial_testing\DOLPHIN\out_pre...,0.023341,0.082082,-0.013263,0.009489,-0.115788,-0.030054,-0.033085,...,0.039947,-0.043441,0.022657,-0.005592,-0.049193,0.035046,-0.062723,-0.016851,0.002809,-0.058603
1,0,HC-10#1,C:\dev\dolphin_initial_testing\DOLPHIN\out_pre...,0.027765,0.083410,-0.013095,0.017957,-0.112048,-0.029861,-0.037895,...,0.032051,-0.032581,0.024607,-0.002800,-0.050379,0.039290,-0.064119,-0.015611,0.008671,-0.051965
111,1,pre-LBD-66#1,C:\dev\dolphin_initial_testing\DOLPHIN\out_pre...,0.019440,0.081620,-0.010041,0.008234,-0.116211,-0.031836,-0.031866,...,0.035564,-0.035388,0.022192,-0.004513,-0.050378,0.040394,-0.061118,-0.020224,-0.002153,-0.059166
83,1,pre-LBD-39#1,C:\dev\dolphin_initial_testing\DOLPHIN\out_pre...,0.017986,0.081279,-0.006191,0.014160,-0.116872,-0.034412,-0.034777,...,0.032320,-0.030438,0.023575,-0.003351,-0.050609,0.043531,-0.059853,-0.019976,-0.001620,-0.055876
29,0,HC-5#1,C:\dev\dolphin_initial_testing\DOLPHIN\out_pre...,0.018274,0.081652,-0.011029,0.007160,-0.116242,-0.031156,-0.032652,...,0.030156,-0.030804,0.021572,-0.003760,-0.049409,0.041013,-0.063045,-0.018963,-0.004065,-0.059114

In [71]:
def x_y_split(df):
    embedding_cols = [c for c in df.columns if c.startswith("emb_")]
    X = df[embedding_cols].values
    y = df["label"].values
    
    return X, y

In [ ]:
df_3_1 = task_freq_dfs.get("3_1")
X, y = x_y_split(df_3_1)
X.shape
y.shape

(147,)

In [75]:
def xgboost_basic_training(df):
    from xgboost import XGBClassifier 
    from sklearn.model_selection import train_test_split
#    X, y = df[X_clmn_name], df[y_clmn_name]
    X,y = x_y_split(df)
    X_train, X_test, y_train, y_test = train_test_split(X, y, random_state=42, test_size=0.2)
    bst = XGBClassifier(n_estimators=2, max_depth=2, learning_rate=1, objective='binary:logistic')
    # fit model
    bst.fit(X_train, y_train)
    # make predictions
    preds = bst.predict(X_test)

    return preds

In [76]:
preds = xgboost_basic_training(df_3_1)
print(preds)

[1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 0 1 1 1 1 1 1 0 1 1 0 0]