In [1]:
import pandas as pd
import json

In [3]:
from pathlib import Path
import pandas as pd
import pathlib

lbd_databse_path = Path("C://dev//dolphin_initial_testing//DOLPHIN//data-raw//LBD_CZ_002")
lbd_databse_path_list = list(lbd_databse_path.rglob("*.svc"))
rows = []
for lbd_file in lbd_databse_path_list:
    name_row = lbd_file.stem
    rows.append(name_row)
rows_df = pd.DataFrame(rows, columns=["file_name"])

In [5]:
rows_df

                                   file_name
0     COBEN-WTABLET-AS-HCD05_w.cz.fnusa.10_1
1     COBEN-WTABLET-AS-HCD05_w.cz.fnusa.15_1
2     COBEN-WTABLET-AS-HCD05_w.cz.fnusa.16_1
3     COBEN-WTABLET-AS-HCD05_w.cz.fnusa.17_1
4     COBEN-WTABLET-AS-HCD05_w.cz.fnusa.18_1
...                                      ...
3444             pre-LBD-99#1_w.cz.fnusa.3_2
3445             pre-LBD-99#1_w.cz.fnusa.3_3
3446             pre-LBD-99#1_w.cz.fnusa.3_4
3447             pre-LBD-99#1_w.cz.fnusa.3_5
3448             pre-LBD-99#1_w.cz.fnusa.9_1

[3449 rows x 1 columns]

In [ ]:
from pathlib import Path
import pathlib
#'C://dev//dolphin_initial_testing//DOLPHIN//xgb_lbd_hc_loo_9_1'
def sumarry_file_to_df(diagnosis_directory_path):
    directory_path = Path(diagnosis_directory_path)
    metrics_paths_list = list(Path(directory_path).rglob('metrics.json'))
    metrics_paths_list
    rows = []
    for metrics_path in metrics_paths_list:
        with open(metrics_path,"r") as f:
            data = json.load(f)
        featureset_row = metrics_path.parent.parent.name
        # Convert top-level metrics
        rows.append({
            "feature set": featureset_row, 
            "balanced_accuracy": data["balanced_accuracy"],
            "mcc": data["mcc"],
            "roc_auc": data["roc_auc"],
            "sensitivity": data["sensitivity"],
            "specificity": data["specificity"]
        })
    df_summary = pd.DataFrame(rows)
    return df_summary

In [3]:

from pathlib import Path
import pathlib
#'C://dev//dolphin_initial_testing//DOLPHIN//xgb_lbd_hc_loo_9_1'
def multitask_sumarry_file_to_df(diagnosis_directory_path):
    directory_path = Path(diagnosis_directory_path)
    metrics_paths_list = list(Path(directory_path).rglob('metrics.json'))
    metrics_paths_list
    rows = []
    for metrics_path in metrics_paths_list:
        with open(metrics_path,"r") as f:
            data = json.load(f)
        featureset_row = metrics_path.parent.parent.name
        task_row = metrics_path.parent.name
        # Convert top-level metrics
        rows.append({
            "feature set": featureset_row, 
            "task": task_row, 
            "balanced_accuracy": data["balanced_accuracy"],
            "mcc": data["mcc"],
            "roc_auc": data["roc_auc"],
            "sensitivity": data["sensitivity"],
            "specificity": data["specificity"]
        })
    df_summary = pd.DataFrame(rows)
    return df_summary

In [76]:
df_summary_lbd_hc = sumarry_file_to_df('C://dev//dolphin_initial_testing//DOLPHIN//xgb_lbd_hc_loo_9_1')
df_summary_ad_hc = sumarry_file_to_df('C://dev//dolphin_initial_testing//DOLPHIN//xgb_ad_hc_loo_9_1')
df_summary_ad_lbd = sumarry_file_to_df('C://dev//dolphin_initial_testing//DOLPHIN//xgb_ad_lbd_loo_9_1')
df_summary_pd_hc = sumarry_file_to_df('C://dev//dolphin_initial_testing//DOLPHIN//xgb_pd_hc_loo_9_1')

In [12]:
df_summary_multi_task_loo = multitask_sumarry_file_to_df('C://dev//dolphin_initial_testing//DOLPHIN//xgb_task_analysis//xgb_loo_9_15_17_19')
df_summary_multi_task_skf = multitask_sumarry_file_to_df('C://dev//dolphin_initial_testing//DOLPHIN//xgb_task_analysis//xgb_skf5_9_15_17_19')

In [13]:
df_summary_multi_task_loo

,feature set,task,balanced_accuracy,mcc,roc_auc,sensitivity,specificity
0,xgb_results_combined_ad_hc_extended_{CV_STRATE...,15_1,0.70,0.377964,0.76,0.8,0.6
1,xgb_results_combined_ad_hc_extended_{CV_STRATE...,16_1,0.45,-0.106600,0.58,0.2,0.7
2,xgb_results_combined_ad_hc_extended_{CV_STRATE...,17_1,0.55,0.106600,0.60,0.8,0.3
3,xgb_results_combined_ad_hc_extended_{CV_STRATE...,19_1,0.50,0.000000,0.68,0.4,0.6
4,xgb_results_combined_ad_hc_extended_{CV_STRATE...,9_1,0.70,0.377964,0.75,0.8,0.6
...,...,...,...,...,...,...,...
135,xgb_results_temporal_pd_hc_extended_{CV_STRATE...,15_1,0.35,-0.353553,0.66,0.0,0.7
136,xgb_results_temporal_pd_hc_extended_{CV_STRATE...,16_1,0.50,0.000000,0.42,0.4,0.6
137,xgb_results_temporal_pd_hc_extended_{CV_STRATE...,17_1,0.55,0.100000,0.50,0.4,0.7
138,xgb_results_temporal_pd_hc_extended_{CV_STRATE...,19_1,0.75,0.533002,0.84,0.6,0.9
139,xgb_results_temporal_pd_hc_extended_{CV_STRATE...,9_1,0.50,0.000000,0.63,0.4,0.6

In [18]:
df_summary_multi_task_loo_1_1_18_1 = multitask_sumarry_file_to_df('C://dev//dolphin_initial_testing//DOLPHIN//xgb_task_analysis_1_18//xgb_loo_1_18')
df_summary_multi_task_skf_1_1_18_1 = multitask_sumarry_file_to_df('C://dev//dolphin_initial_testing//DOLPHIN//xgb_task_analysis_1_18//xgb_skf5_1_18')

In [20]:
df_summary_multi_task_skf_1_1_18_1

,feature set,task,balanced_accuracy,mcc,roc_auc,sensitivity,specificity
0,xgb_results_combined_ad_hc_extended_skf_tasks_...,18_1,0.450000,-0.094491,0.380000,0.400000,0.5
1,xgb_results_combined_ad_hc_extended_skf_tasks_...,1_1,0.400000,-0.200000,0.420000,0.200000,0.6
2,xgb_results_freq_ad_hc_extended_skf_tasks_1_1_...,18_1,0.450000,-0.106600,0.660000,0.200000,0.7
3,xgb_results_freq_ad_hc_extended_skf_tasks_1_1_...,1_1,0.700000,0.377964,0.560000,0.800000,0.6
4,xgb_results_handcrafted_ad_hc_extended_skf_tas...,18_1,0.750000,0.533002,0.620000,0.600000,0.9
5,xgb_results_handcrafted_ad_hc_extended_skf_tas...,1_1,0.500000,0.000000,0.500000,0.600000,0.4
6,xgb_results_handcrafted_comb_emb_ad_hc_extende...,18_1,0.350000,-0.288675,0.280000,0.200000,0.5
7,xgb_results_handcrafted_comb_emb_ad_hc_extende...,1_1,0.500000,0.000000,0.500000,1.000000,0.0
8,xgb_results_handcrafted_frerq_emb_compensated_...,18_1,0.600000,0.213201,0.630000,0.400000,0.8
9,xgb_results_handcrafted_frerq_emb_compensated_...,1_1,0.600000,0.200000,0.640000,0.800000,0.4
10,xgb_results_handcrafted_temp_emb_compensated_a...,18_1,0.400000,-0.277350,0.400000,0.000000,0.8
11,xgb_results_handcrafted_temp_emb_compensated_a...,1_1,0.400000,-0.200000,0.360000,0.200000,0.6
12,xgb_results_temp_ad_hc_extendedskf_tasks_1_1_18_1,18_1,0.300000,-0.426401,0.240000,0.000000,0.6
13,xgb_results_temp_ad_hc_extendedskf_tasks_1_1_18_1,1_1,0.300000,-0.377964,0.420000,0.200000,0.4
14,xgb_results_combined_ad_lbd_extended_skf_tasks...,18_1,0.514286,0.028571,0.657143,0.428571,0.6
15,xgb_results_combined_ad_lbd_extended_skf_tasks...,1_1,0.314286,-0.371429,0.314286,0.428571,0.2
16,xgb_results_freq_ad_lbd_extended_skf_tasks_1_1...,18_1,0.685714,0.371429,0.800000,0.571429,0.8
17,xgb_results_freq_ad_lbd_extended_skf_tasks_1_1...,1_1,0.514286,0.028571,0.371429,0.428571,0.6
18,xgb_results_handcrafted_ad_lbd_extended_skf_ta...,18_1,0.485714,-0.028571,0.714286,0.571429,0.4
19,xgb_results_handcrafted_ad_lbd_extended_skf_ta...,1_1,0.585714,0.169031,0.600000,0.571429,0.6
20,xgb_results_handcrafted_combined_emb_compensat...,18_1,0.657143,0.314286,0.800000,0.714286,0.6
21,xgb_results_handcrafted_combined_emb_compensat...,1_1,0.542857,0.097590,0.542857,0.285714,0.8
22,xgb_results_handcrafted_frerq_emb_compensated_...,18_1,0.585714,0.169031,0.571429,0.571429,0.6
23,xgb_results_handcrafted_frerq_emb_compensated_...,1_1,0.242857,-0.507093,0.371429,0.285714,0.2
24,xgb_results_handcrafted_temporal_emb_compensat...,18_1,0.314286,-0.371429,0.485714,0.428571,0.2
25,xgb_results_handcrafted_temporal_emb_compensat...,1_1,0.657143,0.314286,0.771429,0.714286,0.6
26,xgb_results_temporal_ad_lbd_extended_skf_tasks...,18_1,0.314286,-0.371429,0.400000,0.428571,0.2
27,xgb_results_temporal_ad_lbd_extended_skf_tasks...,1_1,0.757143,0.507093,0.714286,0.714286,0.8
28,xgb_results_comb_lbd_hc_extended_skf_tasks_1_1...,18_1,0.535714,0.070430,0.385714,0.571429,0.5
29,xgb_results_comb_lbd_hc_extended_skf_tasks_1_1...,1_1,0.707143,0.408491,0.685714,0.714286,0.7
30,xgb_results_freq_lbd_hc_extended_skf_tasks_1_1...,18_1,0.364286,-0.271429,0.178571,0.428571,0.3
31,xgb_results_freq_lbd_hc_extended_skf_tasks_1_1...,1_1,0.364286,-0.271429,0.514286,0.428571,0.3
32,xgb_results_handcrafted_combined_emb_lbd_hc_sk...,18_1,0.464286,-0.070430,0.471429,0.428571,0.5
33,xgb_results_handcrafted_combined_emb_lbd_hc_sk...,1_1,0.535714,0.070430,0.571429,0.571429,0.5
34,xgb_results_handcrafted_frerq_emb_lbd_hc_compe...,18_1,0.314286,-0.382518,0.214286,0.428571,0.2
35,xgb_results_handcrafted_frerq_emb_lbd_hc_compe...,1_1,0.485714,-0.028571,0.442857,0.571429,0.4
36,xgb_results_handcrafted_lbd_hc_extended_skf_ta...,18_1,0.557143,0.117698,0.542857,0.714286,0.4
37,xgb_results_handcrafted_lbd_hc_extended_skf_ta...,1_1,0.442857,-0.117698,0.385714,0.285714,0.6
38,xgb_results_handcrafted_temporal_emb_lbd_hc_co...,18_1,0.364286,-0.271429,0.357143,0.428571,0.3
39,xgb_results_handcrafted_temporal_emb_lbd_hc_co...,1_1,0.242857,-0.514286,0.400000,0.285714,0.2
40,xgb_results_temp_lbd_hc_extended_skf_tasks_1_1...,18_1,0.557143,0.117698,0.585714,0.714286,0.4
41,xgb_results_temp_lbd_hc_extended_skf_tasks_1_1...,1_1,0.535714,0.070430,0.471429,0.571429,0.5
42,xgb_results_combined_pd_hc_extended_skf_tasks_...,18_1,0.450000,-0.094491,0.460000,0.400000,0.5
43,xgb_results_combined_pd_hc_extended_skf_tasks_...,1_1,0.600000,0.213201,0.460000,0.400000,0.8
44,xgb_results_freq_pd_hc_extended_skf_tasks_1_1_...,18_1,0.450000,-0.094491,0.360000,0.400000,0.5
45,xgb_results_freq_pd_hc_extended_skf_tasks_1_1_...,1_1,0.650000,0.288675,0.660000,0.600000,0.7
46,xgb_results_handcrafted_comb_emb_pd_hc_extende...,18_1,0.550000,0.094491,0.460000,0.600000,0.5
47,xgb_results_handcrafted_comb_emb_pd_hc_extende...,1_1,0.500000,0.000000,0.400000,0.200000,0.8
48,xgb_results_handcrafted_frerq_emb_pd_hc_extend...,18_1,0.400000,-0.213201,0.400000,0.600000,0.2
49,xgb_results_handcrafted_frerq_emb_pd_hc_extend...,1_1,0.550000,0.138675,0.620000,0.200000,0.9
50,xgb_results_handcrafted_pd_hc_extended_skf_tas...,18_1,0.600000,0.213201,0.660000,0.400000,0.8
51,xgb_results_handcrafted_pd_hc_extended_skf_tas...,1_1,0.500000,0.000000,0.620000,0.600000,0.4
52,xgb_results_handcrafted_temp_emb_pd_hc_extende...,18_1,0.550000,0.094491,0.580000,0.600000,0.5
53,xgb_results_handcrafted_temp_emb_pd_hc_extende...,1_1,0.650000,0.353553,0.740000,0.400000,0.9
54,xgb_results_temporal_pd_hc_extended_skf_tasks_...,18_1,0.550000,0.094491,0.560000,0.600000,0.5
55,xgb_results_temporal_pd_hc_extended_skf_tasks_...,1_1,0.550000,0.100000,0.600000,0.400000,0.7

In [ ]:
df_summary_multi_task_loo.to_csv('xgb_loo_9_15_17_19_summary.csv', sep=';')

In [21]:
df_summary_multi_task_loo_1_1_18_1.to_csv('xgb_loo_1_18_summary.csv', sep=';')

In [ ]:

df_summary_multi_task_skf_1_1_18_1.to_csv('xgb_skf_1_18_summary.csv', sep=';')

:

In [153]:
df_summary_multi_task_loo.groupby('task')[df_summary_multi_task_loo.select_dtypes(include="number").columns].mean()

      balanced_accuracy       mcc   roc_auc  sensitivity  specificity
task
15_1           0.587245  0.169097  0.617143     0.495918     0.678571
16_1           0.476531 -0.044517  0.503418     0.524490     0.428571
17_1           0.555867  0.110978  0.560765     0.579592     0.532143
19_1           0.561480  0.123621  0.618214     0.505102     0.617857
9_1            0.619133  0.240668  0.668997     0.663265     0.575000

In [ ]:
df_summary_ad_lbd

,feature set,balanced_accuracy,mcc,roc_auc,sensitivity,specificity
0,xgb_results_comb_loo_9_1_ad_lbd,0.716667,0.448543,0.766667,0.833333,0.6
1,xgb_results_freq_loo_9_1_ad_lbd,0.633333,0.266667,0.700000,0.666667,0.6
2,xgb_results_handcrafted_combined_emb_loo_9_1_a...,0.650000,0.310530,0.733333,0.500000,0.8
3,xgb_results_handcrafted_frerq_emb_loo_9_1_ad_lbd,0.800000,0.670820,0.800000,1.000000,0.6
4,xgb_results_handcrafted_temporal_emb_loo_9_1_a...,0.533333,0.069007,0.733333,0.666667,0.4
5,xgb_results_hc_loo_9_1_ad_lbd,0.628571,0.292770,0.742857,0.857143,0.4
6,xgb_results_temp_loo_9_1_ad_lbd,0.450000,-0.100000,0.433333,0.500000,0.4

In [78]:
df_summary_ad_hc

,feature set,balanced_accuracy,mcc,roc_auc,sensitivity,specificity
0,xgb_results_comb_loo_9_1_ad_hc,0.70,0.377964,0.77,0.8,0.6
1,xgb_results_freq_loo_9_1_ad_hc,0.70,0.377964,0.81,0.8,0.6
2,xgb_results_handcrafted_combined_emb_loo_9_1_a...,0.70,0.377964,0.68,0.8,0.6
3,xgb_results_handcrafted_frerq_emb_loo_9_1_ad_hc,0.65,0.288675,0.76,0.6,0.7
4,xgb_results_handcrafted_temporal_emb_loo_9_1_a...,0.65,0.288675,0.63,0.6,0.7
5,xgb_results_hc_loo_9_1_ad_hc,0.55,0.100000,0.60,0.4,0.7
6,xgb_results_temp_loo_9_1_ad_hc,0.55,0.094491,0.54,0.6,0.5

In [79]:
df_summary_lbd_hc

,feature set,balanced_accuracy,mcc,roc_auc,sensitivity,specificity
0,xgb_results_comb_loo_9_1_lbd_hc,0.600000,0.200000,0.650000,0.500000,0.7
1,xgb_results_freq_loo_9_1_lbd_hc,0.633333,0.258199,0.650000,0.666667,0.6
2,xgb_results_handcrafted_combined_emb_loo_9_1_l...,0.583333,0.162650,0.533333,0.666667,0.5
3,xgb_results_handcrafted_frerq_emb_loo_9_1_lbd_hc,0.650000,0.313340,0.616667,0.500000,0.8
4,xgb_results_handcrafted_loo_9_1_lbd_hc,0.657143,0.309890,0.628571,0.714286,0.6
5,xgb_results_handcrafted_temporal_emb_loo_9_1_l...,0.700000,0.447214,0.683333,1.000000,0.4
6,xgb_results_temp_loo_9_1_lbd_hc,0.716667,0.422890,0.758333,0.833333,0.6

In [84]:
df_summary_9_1 = pd.concat([df_summary_lbd_hc, df_summary_ad_hc, df_summary_ad_lbd, df_summary_pd_hc], keys=['lbd_hc', 'ad_hc', 'ad_lbd', 'pd_hc'])

In [93]:
df_summary_9_1

                                                feature set  \
lbd_hc 0                    xgb_results_comb_loo_9_1_lbd_hc
       1                    xgb_results_freq_loo_9_1_lbd_hc
       2  xgb_results_handcrafted_combined_emb_loo_9_1_l...
       3   xgb_results_handcrafted_frerq_emb_loo_9_1_lbd_hc
       4             xgb_results_handcrafted_loo_9_1_lbd_hc
       5  xgb_results_handcrafted_temporal_emb_loo_9_1_l...
       6                    xgb_results_temp_loo_9_1_lbd_hc
ad_hc  0                     xgb_results_comb_loo_9_1_ad_hc
       1                     xgb_results_freq_loo_9_1_ad_hc
       2  xgb_results_handcrafted_combined_emb_loo_9_1_a...
       3    xgb_results_handcrafted_frerq_emb_loo_9_1_ad_hc
       4  xgb_results_handcrafted_temporal_emb_loo_9_1_a...
       5                       xgb_results_hc_loo_9_1_ad_hc
       6                     xgb_results_temp_loo_9_1_ad_hc
ad_lbd 0                    xgb_results_comb_loo_9_1_ad_lbd
       1                    xgb_results_freq_loo_9_1_ad_lbd
       2  xgb_results_handcrafted_combined_emb_loo_9_1_a...
       3   xgb_results_handcrafted_frerq_emb_loo_9_1_ad_lbd
       4  xgb_results_handcrafted_temporal_emb_loo_9_1_a...
       5                      xgb_results_hc_loo_9_1_ad_lbd
       6                    xgb_results_temp_loo_9_1_ad_lbd
pd_hc  0                     xgb_results_comb_loo_9_1_pd_hc
       1                     xgb_results_freq_loo_9_1_pd_hc
       2  xgb_results_handcrafted_combined_emb_loo_9_1_p...
       3    xgb_results_handcrafted_frerq_emb_loo_9_1_pd_hc
       4  xgb_results_handcrafted_temporal_emb_loo_9_1_p...
       5                       xgb_results_hc_loo_9_1_pd_hc
       6                     xgb_results_temp_loo_9_1_pd_hc

          balanced_accuracy       mcc   roc_auc  sensitivity  specificity
lbd_hc 0           0.600000  0.200000  0.650000     0.500000          0.7
       1           0.633333  0.258199  0.650000     0.666667          0.6
       2           0.583333  0.162650  0.533333     0.666667          0.5
       3           0.650000  0.313340  0.616667     0.500000          0.8
       4           0.657143  0.309890  0.628571     0.714286          0.6
       5           0.700000  0.447214  0.683333     1.000000          0.4
       6           0.716667  0.422890  0.758333     0.833333          0.6
ad_hc  0           0.700000  0.377964  0.770000     0.800000          0.6
       1           0.700000  0.377964  0.810000     0.800000          0.6
       2           0.700000  0.377964  0.680000     0.800000          0.6
       3           0.650000  0.288675  0.760000     0.600000          0.7
       4           0.650000  0.288675  0.630000     0.600000          0.7
       5           0.550000  0.100000  0.600000     0.400000          0.7
       6           0.550000  0.094491  0.540000     0.600000          0.5
ad_lbd 0           0.716667  0.448543  0.766667     0.833333          0.6
       1           0.633333  0.266667  0.700000     0.666667          0.6
       2           0.650000  0.310530  0.733333     0.500000          0.8
       3           0.800000  0.670820  0.800000     1.000000          0.6
       4           0.533333  0.069007  0.733333     0.666667          0.4
       5           0.628571  0.292770  0.742857     0.857143          0.4
       6           0.450000 -0.100000  0.433333     0.500000          0.4
pd_hc  0           0.600000  0.200000  0.450000     0.800000          0.4
       1           0.500000  0.000000  0.560000     0.600000          0.4
       2           0.650000  0.288675  0.700000     0.800000          0.5
       3           0.700000  0.377964  0.740000     0.800000          0.6
       4           0.700000  0.377964  0.720000     0.800000          0.6
       5           0.550000  0.094491  0.620000     0.600000          0.5
       6           0.550000  0.100000  0.640000     0.400000          0.7

In [82]:
df_summary_lbd_hc.to_csv("./xgb_lbd_hc_loo_9_1_summary.csv", sep = ";")
df_summary_ad_hc.to_csv("./xgb_ad_hc_loo_9_1_summary.csv", sep = ";")
df_summary_ad_lbd.to_csv("./xgb_ad_lbd_loo_9_1_summary.csv", sep = ";")
df_summary_pd_hc.to_csv("./xgb_pd_hc_loo_9_1_summary.csv", sep = ";")

In [27]:
# repetitive takes removed from dataset -> OPTUNA -> skf5, eval ->train/test split
df_summary_multi_task_whole_taskset_loo = multitask_sumarry_file_to_df('C://dev//dolphin_initial_testing//DOLPHIN//xgb_loo_cleaned_dataset')
df_summary_multi_task_whole_taskset_skf = multitask_sumarry_file_to_df('C://dev//dolphin_initial_testing//DOLPHIN//xgb_skf_cleaned_dataset')

In [ ]:
df_summary_multi_task_whole_taskset_loo

,feature set,task,balanced_accuracy,mcc,roc_auc,sensitivity,specificity
0,xgb_results_combined_ad_hc_extended_loo_tasks_...,15_1,0.65,0.353553,0.62,0.4,0.9
1,xgb_results_combined_ad_hc_extended_loo_tasks_...,16_1,0.45,-0.100000,0.44,0.6,0.3
2,xgb_results_combined_ad_hc_extended_loo_tasks_...,17_1,0.25,-0.472456,0.40,0.2,0.3
3,xgb_results_combined_ad_hc_extended_loo_tasks_...,18_1,0.45,-0.100000,0.46,0.6,0.3
4,xgb_results_combined_ad_hc_extended_loo_tasks_...,19_1,0.60,0.213201,0.70,0.4,0.8
...,...,...,...,...,...,...,...
191,xgb_results_temporal_pd_hc_extended_loo_tasks_...,17_1,0.70,0.377964,0.80,0.8,0.6
192,xgb_results_temporal_pd_hc_extended_loo_tasks_...,18_1,0.35,-0.288675,0.42,0.2,0.5
193,xgb_results_temporal_pd_hc_extended_loo_tasks_...,19_1,0.65,0.288675,0.77,0.6,0.7
194,xgb_results_temporal_pd_hc_extended_loo_tasks_...,1_1,0.45,-0.106600,0.42,0.2,0.7
195,xgb_results_temporal_pd_hc_extended_loo_tasks_...,9_1,0.50,0.000000,0.68,0.2,0.8

In [30]:
df_summary_multi_task_whole_taskset_skf

,feature set,task,balanced_accuracy,mcc,roc_auc,sensitivity,specificity
0,xgb_results_combined_ad_hc_extended_skf_tasks_...,15_1,0.65,0.353553,0.56,0.4,0.9
1,xgb_results_combined_ad_hc_extended_skf_tasks_...,16_1,0.50,0.000000,0.56,0.2,0.8
2,xgb_results_combined_ad_hc_extended_skf_tasks_...,17_1,0.55,0.094491,0.48,0.6,0.5
3,xgb_results_combined_ad_hc_extended_skf_tasks_...,18_1,0.20,-0.577350,0.26,0.0,0.4
4,xgb_results_combined_ad_hc_extended_skf_tasks_...,19_1,0.60,0.213201,0.60,0.4,0.8
...,...,...,...,...,...,...,...
191,xgb_results_temporal_pd_hc_extended_skf_tasks_...,17_1,0.60,0.188982,0.76,0.6,0.6
192,xgb_results_temporal_pd_hc_extended_skf_tasks_...,18_1,0.35,-0.288675,0.34,0.4,0.3
193,xgb_results_temporal_pd_hc_extended_skf_tasks_...,19_1,0.60,0.188982,0.72,0.6,0.6
194,xgb_results_temporal_pd_hc_extended_skf_tasks_...,1_1,0.45,-0.106600,0.56,0.2,0.7
195,xgb_results_temporal_pd_hc_extended_skf_tasks_...,9_1,0.60,0.200000,0.60,0.8,0.4

In [31]:
df_summary_multi_task_whole_taskset_loo.to_csv('xgb_loo_cleaned_dataset_summary.csv', sep=';')
df_summary_multi_task_whole_taskset_skf.to_csv('xgb_skf_cleaned_dataset_summary.csv', sep=';')